//! Every frame the Python server knows, with every field set, parses into these types and
//! serializes back to the same JSON. The fixture is generated by the server
//! (`scripts/dump_wire_examples.py`); regenerate it there and copy it here.

use rekuest_protocol::messages::{Envelope, ToAgentFrame};
use serde_json::{Map, Value};

/// A declaration the protocol does not interpret: servers and tests read it as a map.
type AnyDeclaration = Map<String, Value>;

fn fixture() -> Value {
    serde_json::from_str(include_str!("fixtures/agent_wire_examples.json")).unwrap()
}

fn frames(direction: &str) -> Vec<(String, Value)> {
    fixture()[direction]
        .as_object()
        .unwrap()
        .iter()
        .map(|(kind, frame)| (kind.clone(), frame.clone()))
        .collect()
}

#[test]
fn every_from_agent_frame_round_trips() {
    let frames = frames("from_agent");
    assert_eq!(
        frames.len(),
        28,
        "the fixture lost or gained a message type"
    );
    for (kind, frame) in frames {
        let parsed: Envelope<AnyDeclaration> = serde_json::from_value(frame.clone())
            .unwrap_or_else(|e| panic!("{kind} does not parse: {e}\n{frame}"));
        let back = serde_json::to_value(&parsed).unwrap();
        assert_eq!(back, frame, "{kind} does not serialize back unchanged");
    }
}

#[test]
fn every_to_agent_frame_round_trips() {
    let frames = frames("to_agent");
    assert_eq!(
        frames.len(),
        38,
        "the fixture lost or gained a message type"
    );
    for (kind, frame) in frames {
        let parsed: ToAgentFrame = serde_json::from_value(frame.clone())
            .unwrap_or_else(|e| panic!("{kind} does not parse: {e}\n{frame}"));
        assert!(
            !matches!(parsed.message, rekuest_protocol::messages::ToAgent::Unknown),
            "{kind} is not modelled (it fell into Unknown)"
        );
        let back = serde_json::to_value(&parsed).unwrap();
        assert_eq!(back, frame, "{kind} does not serialize back unchanged");
    }
}
